### ISSUE TITLE
Handling of `finally` blocks

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#1]
Example:

``` kotlin
async {
    try {
        ...
        try {
            await(...) // suspension point
        } finally {
           foo()
        }
        ...
    } finally {
        bar()
   }
}
```

A controller should be able to abort the execution of a coroutine. In that case it needs to have an option of executing all `finally` blocks whose corresponding `try` sections have been entered, but that were not executed themselves yet.

In the example above, at a suspension point inside the inner try, the controller must be able to execute both `finally` blocks: the one with `foo()` and the one with `bar()`.

This relates to #10: Disposable iterators & `for`-loops

**Comment by abreslav** [comment]
Questions:

- How do we name the corresponding function in `Continuation` (#20)?
  - `executeFinallyBlocks()`?
- Does it invalidate the coroutine?

**Comment by elizarov** [comment]
The current design does not have a special treatment of finally blocks. They can be always invoked by "throwing an exception" via `resumeWithException`. It coverts all the various use-cases that we were able to identify.
