### ISSUE TITLE
Coroutine Example has Int Overflow error

### ISSUE THREAD

**Issue by MrThreepwood** [Kotlin/kotlin-coroutines#110]
I was reading through this article: https://kotlinlang.org/docs/tutorials/coroutines-basic-jvm.html about kotlin coroutines and decided to test it out myself and compare it to GO. (It actually compares fairly favorably). However, the results were different. I then noticed the answer in Kotlin is wrong, the value should be the high value, plus the low value (100,000,001) multiplied by number of iterations over 2 (500,000). After making a new inline function (sumByLong), I got the correct answer. So, technically not an issue in the libraries, but for those reading it might be good to point out why you get the wrong value.

**Comment by elizarov** [comment]
Thanks. Reposted your problem here https://youtrack.jetbrains.com/issue/KT-27702
