### ISSUE TITLE
Naming: generate/yield

### ISSUE THREAD

**Issue by fvasco** [Kotlin/kotlin-coroutines#13]
The function _generate_ is used to generate a Kotlin sequence but some Java 8 compatible application may generate a _Stream_ (or any other type).

Consider to use a more specific function name like _generateSequence_ (and counterpart _generateStream_), or _asyncSequence_ (and _asyncStream_),  or directly _sequence_ (and _stream_).

**Comment by abreslav** [comment]
The examples given so far are by no means a proposal for additions to the standard library, but I see your concern

**Comment by abreslav** [comment]
Names to be picked here:
- generate/sequence/...
- yield
- yieldAll/yieldMany

**Comment by elizarov** [comment]
The pair `buildSequence`/`yield` as currently defined in Kotlin standard library seems to work fine.
