### ISSUE TITLE
Stack spilling

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#14]
When a suspension point occurs in the middle of an argument list, e.g.:

``` kotlin
foo(a(), b(), await(...), c())
```

we need to evaluate the first two arguments and save them to fields, then suspend, then, upon resumption, load them, compute the last argument and execute `foo()`

**Comment by abreslav** [comment]
A case of constructor calls is important here:

``` kotlin
Foo(a(), await(...))
```

What we do
- compute `a()`
- suspend, when resumed
- create an instance of `Foo`
- call `Foo.<init>`

Problem: when is the `Foo` class loaded?
Why it's relevant: it affects whether its `<clinit>` is called before or after computing `a()`.

Normally, a constructor call is computed as follows:

```
NEW Foo
DUP
INVOKE a()
INVOKE Foo.<init>()
```

Which means that the instance of `Foo` is created **before** the call to `a()`

**Comment by dzharkov** [comment]
In the current implementation, a suspension call may slightly change the point where `<clinit>` is called, and it should not be very important
