### ISSUE TITLE
Suspension point syntax

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#16]
Options:
- a suspension point is simply a call to a suspending function: `await(foo)`
- a suspending call is prefixed with a symbol: `&await(foo)` or `^await(foo)`

On the one hand, the less syntax we introduce, the better.
On the other hand it may be appealing to always see suspending calls clearly in the code.

P.S. Note Bjarne Stroustrup's observation that for new features people usually want loud syntax, but when they become familiar, people want to be rid of the once appealing loudness.

**Comment by Takhion** [comment]
I think that because the name of the suspending calls are variable, there should be a symbol prefix before them, or it will be **very** hard to understand what's going on.
(For others that want to "vote" on this, please use emoji reactions!)

**Comment by mplatvoet** [comment]
To me it's not entirely clear what the benefit is of communicating something is a suspending function. I wonder how this is different from any other blocking function from the perspective of the caller. I think it can be helpful to list what the benefits of this communication is in order to make a sound decision. I can't think of any benefits but I bet others can.

**Comment by Takhion** [comment]
The problem is it's not just _blocking_ the execution, it's actually jumping somewhere, much like a dynamic goto statement would

**Comment by mplatvoet** [comment]
I understand what it does, I'm wondering why you should communicate that at the call site? Would the fact that something is (potentially) a suspending call change any of the code on the call side? Does it change the essence of how you read/interpret the code? At the moment I don't think so, see the following example:
```
async {
   val bar = ^await(foo)
}
//versus

async {
   val bar = get(foo) // blocking get
}
```
I don't feel I gain anything by knowing something is a suspending call. The code remains essentially the same. But maybe I'm overlooking something and I'm hoping others can point that out.

Nb. I think decisions on features should be made by arguments, not by voting.

**Comment by abreslav** [comment]
> I think it can be helpful to list what the benefits of this communication is in order to make a sound decision.

One thing that comes to mind: the code on either side of a suspending call can be executed on different threads

**Comment by Takhion** [comment]
Exactly, while using a callback would make it clear that that piece of code might potentially run on a different thread, it's completely invisible in a coroutine. Also, if the coroutine allows to reset the state or something, it could be hard to understand why the execution is not reaching some code.

**Comment by abreslav** [comment]
> Also, if the coroutine allows to reset the state or something, it could be hard to understand why the execution is not reaching some code.

This can hardly be helped by explicitly marking suspension points, IMO

**Comment by Takhion** [comment]
True, but at least it's an indication that this is not a normal snipped of code but a coroutine.

**Comment by abreslav** [comment]
> True, but at least it's an indication that this is not a normal snipped of code but a coroutine.

For the record, an option here is to indicate the whole coroutine body at the call site, see #21

**Comment by Takhion** [comment]
but a coroutine becomes something different from a "normal" callback only when a suspension call is used, otherwise once the code inside starts running, it runs all of it

**Comment by abreslav** [comment]
> But a coroutine becomes something different from a "normal" callback only when a suspension call is used, otherwise once the code inside starts running, it runs all of it.

Good point

**Comment by Takhion** [comment]
@abreslav I'm wondering about one thing: because a coroutine body _resembles_ a lambda but it's not (different type checking, suspend methods in the scope, etc.), one can't save it as an object and later feed it to a method like `async`, right?

**Comment by abreslav** [comment]
Not directly, but one can write a very easy "builder" that returns the `Coroutine`: representation of the body:

```
fun asyncBody(coroutine c: () -> Coroutine<AsyncController>) = c
```

**Comment by stepank** [comment]
I might be wrong, but it seems to me that Kotlin code will only occasionally (if ever) be written in text editors lacking syntax highlighting. Therefore, I'd say that syntax highlighting can solve the problem of putting all the necessary accents very efficiently and special syntax for calls to suspending functions can hardly be justified. Moreover, this approach covers both scenarios of early adoption when people want some construct to be clearly visibly and of later use when everybody is used to this construct and does not need the initially set accent anymore.

However, it seems appealing to have parenthesis for calls to suspending functions optional, so that `await`s looked like this:

`var something = await read(...)`

and calls to other suspending methods like the ones described [here](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#a-builder-and-controller-for-asyncio) could still look like this:

`var something = aRead(...)`

My reasoning here is that `await` acts as (but is actually not) a syntax construct in the former case, but it is sort of implicit and resembles suspending methods in Quasar (and afaik Golang) in the latter case.

**Comment by udalov** [comment]
@stepank 

> it seems to me that Kotlin code will only occasionally (if ever) be written in text editors lacking syntax highlighting

BTW, the simplest example of a text editor (or to be precise, viewer) lacking syntax highlighting where Kotlin is surely going to be used is GitHub.

**Comment by stepank** [comment]
@udalov 
True for comments, but not for the code viewer. [This file](https://github.com/Kotlin/kotlin-coroutines/blob/master/examples/coroutines.kt) definitely looks highlighted for me. Not that highlighting is very bright, but it is definitely there. So maybe it's only a matter of time when Kotlin's async/await will be properly highlighted.

**Comment by yole** [comment]
@stepank It's not a matter of time. "async" and "await" are library functions, and detecting that they need to be highlighted in a special way requires much deeper analysis than what regexp-based syntax highlighters such as the one used by GitHub are able to perform.

**Comment by stepank** [comment]
@yole 
I totally understand that they are library functions (and I actually find this fact absolutely wonderful). Though I expect (maybe I should not) that only a narrow subset of such functions will be used more or less often, so it will be possible to cover these usages with simple regexp-based syntax highlighter. I concede that this approach cannot cover every usage of suspending functions, but it seems to me like an acceptable price for not cluttering the code with additional syntax.

**Comment by elizarov** [comment]
I'll allude to the Stroustrup's observation at the topic start. It does require loud syntax. Take a look the the last slide of coroutine presentation https://www.youtube.com/watch?v=4W3ruTWUhpw&noredirect=1 (Appendix: Serializable Coroutines?). It is quite non-obvious where are suspending calls in the presented code (await and yield do not really suffer from this problem, of course). If initial release does not require any call-site indication for suspention, then it is going to be hard to add it in the future. On the other side, if initial release requires some syntactic form to mark suspending call sites, then this requirement can always be relaxed in the future.

However, `&await(foo)` and `^await(foo)` look cryptic and very un-Kotlin. Kotlin does not even have shift and bitwise operators, having replaced them with infix functions for good. Less often used features should have more verbose and more _mnemonic_ names.

I'd suggest to start with `suspend` keyword for the purpose of marking suspending calls, as in `suspend await(foo)`. Yes, it is verbose, but it makes immediately obvious for the reader what is going on without digging into the language docs. This is important while we are in the phase when people are just becoming familiar with this new feature. Shorter syntax can always be rolled out later.

**Comment by dzharkov** [comment]
I like the idea about `suspend ` prefix, but we should consider the problems with infix calls
```
infix fun Int.foo(block: () -> Unit) {}

fun bar() {
    val suspend = 1
    suspend foo { // kind of ambiguity here
        println("")
    }
}
```

**Comment by elizarov** [comment]
A few reasonable approaches I see here for `suspend`: 
1. make suspend a full-blown keyword (backward-incompatible)
2. make suspend a soft-keyword and resolve ambiguity 
2.1 resolve ambiguity in favour of suspend as keyword (less backwards incompatibility, but there is still some) 
2.1.a + warn in case of ambiguity
2.1.b + error in case of ambiguity
2.2 resolve ambiguity in favour of infix calls (fully backwards compatible)
2.2.a + warn in case of ambiguity

**Comment by ilya-g** [comment]
@elizarov please consider how this keyword would mix with suspend properties #24 #25

**Comment by elizarov** [comment]
Having really thought about coroutines I don't see a need for a special syntax anymore. On the contrary, we shall plan to make suspensions ubiquitous and efficient. IDE shall provide some visual cues about suspend calls. That should be enough.
