### ISSUE TITLE
Thread-safety for fields representing variables

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#17]
Locals of a coroutine (at least some of them) are stored as fields of the state machine object.
Since the coroutine may be resumed on a thread different from the one it has been suspended from, access to those fields needs to be thread-safe.

The easiest way is to make them all `volatile`, or make one of them `volatile` and piggyback the rest (likely, this is the `label` field that holds the current state of a state machine).

Issue:
- some coroutines won't be called from different threads (e.g. generators), must they pay the runtime penalty of `volatile` reads/writes too?

**Comment by dzharkov** [comment]
It seems that these fields (and also `controller` and `label`) don't have to be volatile because the majority of async frameworks guarantees happens-before relation between putting the task into the queue and the beginning of its execution. 
Anyway, it should not be that hard to implement Controller to follow this rule.

Thanks to @elizarov for this insight

**Comment by dzharkov** [comment]
Also, see https://github.com/Kotlin/kotlin-coroutines/issues/63 as a demonstration of performance problems that may arise when using volatile fields

**Comment by testn** [comment]
Instead of having to make them a volatile field, is it possible to make the coroutine handling to establish "happen-before" relationship when it switches from one thread to another?

**Comment by dzharkov** [comment]
@testn As I stated above it already works for all cases that I know.
On new implementations, I'm sure that it's possible, as there are a lot of safe-publication methods that IMHO anyway must be applied when passing a continuation instance from one thread to another and guarantees necessary happens-before:
- storing a continuation into a volatile field
- putting it into `ConcurrentLinkedQueue`
- starting a new thread

And  many others
