### ISSUE TITLE
Don't hold locals longer than they are alive

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#18]
When a local variable goes out of scope, the corresponding field needs to be nullified.

Example:

``` kotlin
async {
    val foo = ...
    await(x)
    bar(foo)
    // nullify foo at this point!
    await(y)
    await(z)
}
```

Variable `foo` is never used after the call to `bar()`, so its field should not retain the reference, otherwise a memory leak may occur

**Comment by elizarov** [comment]
Still an issue. See here: https://youtrack.jetbrains.com/issue/KT-16222
