### ISSUE TITLE
Result and exception handlers: names and signatures

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#19]
### Naming
- handleResult/handleException
- complete/unhandledException
- resultHandler/exceptionHandler
### Parameters

We could omit passing a continuation parameter to such handlers, because the coroutine can not be resumed any more. But it could be reset (#29)  or introspected (#28), so it may make sense to pass a `Continuation<Nothing>` to termination handlers.
### Return types

Only `Unit` for now. If we find use cases for non-unit returns, we'll reconsider this.
### Syntax

Should we have a special modifier for handlers?

```
handler fun handleResult(...) { ... }
handler fun handleException(...) { ... }
```

Or re-use `operator`?

```
operator fun handleResult(...) { ... }
operator fun handleException(...) { ... }
```

**Comment by dzharkov** [comment]
Should we allow non-Unit return type for handlers?
I can't see any bad consequences if we do, but at the same time I have no pragmatic use cases either

**Comment by abreslav** [comment]
@dzharkov I'd prohibit them for now. If we find use cases for it, we'll lift this restriction

**Comment by elizarov** [comment]
Closed. Obsolete.
