### ISSUE TITLE
Coroutine-like constructs in other languages

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#2]
- C#
  - [Proposal to untie C#'s async/await from Task](https://github.com/dotnet/roslyn/issues/7169)
  - [MSDN: Asynchronous Programming with Async and Await](https://msdn.microsoft.com/en-us/library/hh191443.aspx)
  - [Asynchrony in C#](https://blogs.msdn.microsoft.com/ericlippert/2010/10/28/asynchrony-in-c-5-part-one/) by Eric Lippert
  - [Asynchronous Programming - Pause and Play with Await](https://msdn.microsoft.com/en-us/magazine/hh456403.aspx) by Mads Torgersen
  - [Asynchronous Programming - Async Performance: Understanding the Costs of Async and Await](https://msdn.microsoft.com/en-us/magazine/hh456402.aspx)
    by Stephen Toub

**Comment by abreslav** [comment]
- C++
 - [Coroutines belong in a TS](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0158r0.html)
 - [resumable functions - async and await](http://meetingcpp.com/index.php/br/items/resumable-functions-async-and-await.html)

**Comment by abreslav** [comment]
* Dart
 - https://www.dartlang.org/articles/await-async/

**Comment by abreslav** [comment]
* JavaScript
 - https://davidwalsh.name/async-generators

**Comment by abreslav** [comment]
* F#
  - [Asynchronous Workflows](https://msdn.microsoft.com/en-us/library/dd233250.aspx)

**Comment by yole** [comment]
Python: [PEP 492](https://www.python.org/dev/peps/pep-0492/)

**Comment by yole** [comment]
Typescript: [async/await spec](https://github.com/Microsoft/TypeScript/issues/1664)

**Comment by daurnimator** [comment]
Lua: http://www.lua.org/manual/5.3/manual.html#2.6

Available since Lua 5.0 (released 2003)

**Comment by pniederw** [comment]
* Scala
  * [SIP-22 - Async](http://docs.scala-lang.org/sips/pending/async.html)
  * [scala/async](https://github.com/scala/async) (implementation of SIP-22)

**Comment by abreslav** [comment]
MLVM: [Coroutines for Java](http://ssw.jku.at/General/Staff/LS/coro/)

**Comment by abreslav** [comment]
Hack: https://docs.hhvm.com/hack/async/introduction

**Comment by abreslav** [comment]
Python asynchronous comprehensions: https://www.python.org/dev/peps/pep-0530/

**Comment by IamSungod** [comment]
Clojure core.async : https://github.com/clojure/core.async

**Comment by elizarov** [comment]
Closed. Obsolete. Thanks everybody for feedback!
