### ISSUE TITLE
Naming: members of Coroutine and Continuation

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#20]
Coroutine:
- entryPoint/firstStep/start

Continuation:
- resume/run/next
- resumeWithException/resumeExceptionally/exception
- executeFinallyBlocks (#1)

**Comment by elizarov** [comment]
The current resolution of `resume` and `resumeWithException` seems to be fine with everybody.

**Comment by elizarov** [comment]
Closed. Ship sailed.
