### ISSUE TITLE
Coroutine builder syntax

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#21]
### Current proposal
- `fun <T> async(coroutine c: () -> Coroutine<AsyncController<T>>): Future<T>`
### Modifier on the whole function?
- con: there may be many parameters
### Shorter word for the parameter modifier?
- co/cofun
### Modifier on the parameter type?
- `fun <T> async(c: cofun() => AsyncController<T>)`
- con: too much syntax
- note: make sure the passed lambda may have a receiver type: `Foo.() -> Coroutine<...>`
### Call-site syntax

```
async &{
    ...
}
```

**Comment by mikehearn** [comment]
I like the current proposal. Coroutine is not a modifier that will be typed very frequently. And I don't see why a special syntax to define such a lambda is necessary. If people can benefit from seeing that the lambda is special and it's not obvious from the contents, perhaps the IDE could highlight the lambda brackets or background differently. Then it's optional for the user.

**Comment by dzharkov** [comment]
It's been decided to leave current proposal as is
