### ISSUE TITLE
Allow property accessors as suspension points?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#24]
It's not easy, because there's no place to pass the continuation parameter to.

**Comment by elizarov** [comment]
With the new continuation-less suspend function convention we can, theoretically, support suspendable getters. The only missing piece is some kind of compelling use-case for them.

**Comment by dzharkov** [comment]
Properties might be useful for asynchronous work with DB entities.

**Comment by elizarov** [comment]
The resolution is that it will not be available in 1.1, but in some future release.

**Comment by sanity** [comment]
Just chiming in, I also have a use-case for being able to suspend a getter, explanation [here](https://www.reddit.com/r/java/comments/61ur13/vaadin_framework_is_a_unique_java_ui_library_in/dfigf9g/?context=3)

**Comment by LouisCAD** [comment]
Suspend properties have plenty of use cases that could benefit.
An important category is getting properties that need to be fetched from a non local place such as a remote device.
As I deal with BluetoothGatt, I see it could be useful to get info from non cached characteristics for example. Same to write some info through characteristics, while making sure the write has been fully complete (comes from a callback in Android, that I can use to resume the continuation).

**Comment by elizarov** [comment]
Use-cases are abound. However, to keep this thread updated with the fresh information, there are also drawback. For one, according to Kotlin Style guide properties are assumed to used for something that computes quickly. Making suspending properties somewhat flies right into the face of this recommendation.

**Comment by unicomp21** [comment]
Why not just use getter methods?

**Comment by elizarov** [comment]
Getter methods is what you are forced to do now, while suspending properties are not supported. Whether we have to support suspending properties despite them being in conflict with Kotlin style is an open question. No decision have been made yet.

**Comment by bamboo** [comment]
I don't see a conflict between _computes quickly_ and _computes asynchronously_.

**Comment by LouisCAD** [comment]
@bamboo Asynchronous computation is rarely the same definition of "quick", and by allowing suspending properties, you inherently allow slow properties (in my Bluetooth example, the higher the network congestion, the slower the retrieving), or properties that never resume the continuation

**Comment by bamboo** [comment]
> ... by allowing suspending properties, you inherently allow slow properties

Slow properties are already allowed Today, I say it a bit tongue in cheek but I mean it.

Arguing from another perspective, it's my prerogative as a language user to decide if I should model something as a property or as a function, as a synchronous or as potentially asynchronous computations.

Recommendations shouldn't get in the way of expression.

**Comment by bj0** [comment]
Isn't the purpose of `lazy` to allow you to have a "non-quick" property (that's cached).  It seems natural to extend this to a suspendable `lazy` at least, for caching an asynchronous computation.

**Comment by zach-klippenstein** [comment]
It's notable that the top-level `coroutineContext` property is defined as a `suspend val` too.

**Comment by sanity** [comment]
Just wanted to check in on this, I'm assuming we still can't suspend on property accessors?

I'm guessing the syntax might be something like:

```kotlin
val x suspend get() = suspendingFunction()
```

**Comment by elizarov** [comment]
See here https://youtrack.jetbrains.com/issue/KT-15555
