### ISSUE TITLE
Syntax for chained coroutines with suspend/generate combo

### ISSUE THREAD

**Issue by orangy** [Kotlin/kotlin-coroutines#27]
It's quite common to have chained calls into nested coroutines like these:

```
   val value = await(async { ... long work ... })
```

or

```
yieldAll(generate { yield(1); yield(2); })
```

With current strict function call syntax it will need lambdas in parentheses, as shown above. One can make a combo function, like `awaitAsync` that combines those two, but it's not so composable.

**Comment by abreslav** [comment]
An option would be saying:

``` kotlin
   val value = async { ... long work ... }.await()
```

**Comment by ilya-g** [comment]
What is the point of saying `val value = await(async { ... long work ... })`, when we're already inside an `async`-coroutine? 
Isn't it the same as just `val value =  ... long work ...` or `val value = run { ... long work ... }`?

**Comment by abreslav** [comment]
@orangy ^^^

**Comment by orangy** [comment]
It's about slicing work. E.g. if async is implemented on thread pool or event loop, `run {}` will consume thread and prevent other (probably fast) items from executing. `await async` would schedule job in shared queue, thus sharing "time" with other work items. An example would be game loop, where even complex AI logic is commonly split into several `await async` pieces so that other actors can proceed without interruption.

**Comment by ilya-g** [comment]
We have discussed it and found that generally `await(async { body })` is equivalent to introducing a yielding suspension (like [Task.Yield](http://stackoverflow.com/questions/22645024/when-would-i-use-task-yield) in .NET) and continuing `body` after it:

```
...
await(asyncYield()) // may be shortened to 'suspend' 
body
...
```

**Comment by elizarov** [comment]
The consensus seem to be shifting to ` val value = asyncWork().await()`. The `kotlinx.coroutines` was already updated. The draft KEEP with an updated sample for post 1.1-M04 release is available in this branch: https://github.com/Kotlin/kotlin-coroutines/blob/revision-2.1/kotlin-coroutines-informal.md

**Comment by elizarov** [comment]
Closed. Obsolete.
