### ISSUE TITLE
Against the async/await approach

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#3]
- Bob Nystrom, [What Color is Your Function?](http://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/)
- [Coroutines belong in a TS](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0158r0.html) — on not having coroutines in C++71

**Comment by abreslav** [comment]
Ron Pressler's talk on scoped continuations: http://blog.paralleluniverse.co/2015/08/07/scoped-continuations/

**Comment by abreslav** [comment]
General argument:
- why use stack-less continuations when we could use scoped continuations?

The limitations of the stack-less approach are known, and people seem to still use it profitably in many languages. Plus, see #35 for more details

**Comment by elizarov** [comment]
This is no longer applicable to current Kotlin's design since "what color is your code" problems are much less pronouced in Kotlin, since it does not follow `async`/`await` design of other languages
