### ISSUE TITLE
Extend the state machine class from the controller to economize on allocations?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#30]
Currently, one instance is created for the coroutine, and, for many cases, at least another one — for its controller (yet another may be created for the result of a builder, but often times that one can be merged with the controller, see [examples/async-optimized.kt](../blob/master/examples/async-optimized.kt#L43).

Can we improve on this and somehow merge the (compiler generated) coroutine and the (user-written) controller into one? E.g. extend the coroutine class from a controller class when an annotation is provided?

An obvious issue here would be passing constructor arguments to the controller, for example

**Comment by elizarov** [comment]
Closed. Obsolete. Will not fix. There are a few objects for a typical coroutine. Does not seem to a nice way to merge classes. However, the other object may be singleton. See https://youtrack.jetbrains.com/issue/KT-27704
