### ISSUE TITLE
Interaction with Java interop?

### ISSUE THREAD

**Issue by mikehearn** [Kotlin/kotlin-coroutines#34]
How does Java interop work with this?

Let's say that inside a continuation I call into a Java library, which, in turn, then calls back into my code via a lambda. And then I attempt to suspend. There are non-instrumented Java methods on the stack now, so the state machine won't work properly. Somehow the compiler would have to know to forbid this, I guess?

This concern is one reason I wonder to what extent this feature competes with/would replace Quasar.

**Comment by orangy** [comment]
As far as I understand, calling suspending methods is allowed only directly in the coroutine body, not in any lambda, local function, local class, anonymous object, etc. It should be relaxed for inline lambdas, though, so `synchronized`-like function still works.

**Comment by mikehearn** [comment]
So even calling a regular Kotlin method on the same class that then calls suspend won't be allowed? This would seem to be quite limiting.

By way of contrast, when Quasar rewrites a methods bytecode, it remains usable from both continuation and non-continuation based callers, and it rewrites any methods that could be on the stack at the time a suspension occurs.

**Comment by orangy** [comment]
Correct, calling suspension method is not possible from outside of coroutine without explicitly passing second parameter. So you can create a suspension method, that calls another suspension method with the same continuation without a problem, but you cannot call a regular method and magically get suspension inside of it. Quasar instruments code on the fly, it has all the stack information, and implements more or less "whole program coroutines". We don't have such a goal for Kotlin language feature.

**Comment by rbygrave** [comment]
> We don't have such a goal for Kotlin language feature.

Hmmm, that might have just popped my bubble :)

It could be just my viewpoint but ... I suspect a reasonable number of people will be looking at "coroutines" from a "Quasar" perspective.  It might be really good to document more explicitly the planned limitations and why those limitations are put in place from that angle.

It sounds like this goal restrictions on "Kotlin coroutines" can then be implemented without any need for AOP and possibly that implies that Kotlin will supply a runtime library to execute the coroutines (and hence there won't be a need for Quasar).

Mike will know more about this but I got the impression from following Quasar that there are potential changes in Java 9 wrt Quasar's need to instrument the suspension points (and that the need of AOP might be greatly reduced at that point).  I don't know how accurate that impression is.

For me I'm seeing "Kotlin coroutines" in a different light now though.

**Comment by mplatvoet** [comment]
C# seems to do pretty well with a similar implementation. I don't find this really limiting. This way it's just Tasks/Futures/Promises that can be passed around and waited on in the right async context.

**Comment by rbygrave** [comment]
Thanks Mark. Personally I don't have enough knowledge or experience to add much here.  I've been watching Quasar for a while and remember the "jvm green threads" days (and not exposed to C# to any major extent) so that influences my thinking somewhat .

What I **suspect** (for what it's worth):
- There is a performance cost and complexity cost in making a method "async" aware and if this done explicitly via async / await / yield this can be good and practical (ala peoples experience with C#) 
- It is always good to keep things as simple as possible (and maybe the Quasar approach exceeds the complexity/benefit quota)

So yes, I can understand why "coroutines" is probably not what I originally expected.  I need to do more learning here. I have not yet seen an example that makes use of a ExecutorService (like ForkJoinPool), maybe I've been thinking in "Fiber mode" too much.

Cheers, Rob.

**Comment by abreslav** [comment]
Please note issue #3

**Comment by mikehearn** [comment]
If a coroutine calls into another Kotlin method on the same class (or package class), then can that method also have a coroutine-usable version generated by the compiler? So something like this would work:

``` kotlin
class Foo {
    fun a() {
        async {
           val r = getSomeResult()
        }
    }

    suspendable fun getSomeResult() {
        return future.await();
    }
}
```

Having to make all the functions inline seems not ideal from an efficiency or debuggability perspective.

**Comment by mikehearn** [comment]
@rbygrave In Java 9 having to annotate methods with @Suspendable is no longer necessary because the methods that need to have their bytecode rewritten can be identified on the fly. The advantage is that you can use code that was never designed with suspension in mind, like the callback example in my first comment. The disadvantage is that this kind of technique pushes even HotSpot to the limits of its technology, which is why it's only available in an unreleased JVM. You can forget about it on Android. For more limited JVMs it's back to annotating all the possible paths that lead to a suspend point and then doing the instrumentation ahead of time.

I can see that Kotlin's approach has some advantages: it's tighter, less dependent on runtime JVM magic (which can never be entirely invisible), very likely to be more efficient, would have full support from the IDE and so on. For something like generators/yield you don't want the Quasar approach, it's too complicated and heavy. The big downside is that you can't take an arbitrary (large) piece of code and use it as a coroutine.

Can well be that both techniques end up living side by side peacefully.

**Comment by abreslav** [comment]
> If a coroutine calls into another Kotlin method on the same class (or package class), then can that method also have a coroutine-usable version generated by the compiler?

Created an issue for it: #36

**Comment by rbygrave** [comment]
Thanks Andrey for the references.  Thanks Mike for the excellent summary above.

> Can well be that both techniques end up living side by side peacefully.

Yes, I'm seeing that the more I look at this.

**Comment by abreslav** [comment]
After speaking to Quasar people, I've got an idea that we may integrate the Quasar approach as an optional extension to stack-less coroutines: see #41

**Comment by abreslav** [comment]
Closing this in favor of #36 and #41
