### ISSUE TITLE
Coroutine-transparent functions?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#36]
See [this comment](https://github.com/Kotlin/kotlin-coroutines/issues/34#issuecomment-212319140)

> If a coroutine calls into another Kotlin method on the same class (or package class), then can that method also have a coroutine-usable version generated by the compiler? So something like this would work:

```
class Foo {
    fun a() {
        async {
           val r = getSomeResult()
        }
    }

    suspendable fun getSomeResult() {
        return future.await();
    }
}
```

> Having to make all the functions inline seems not ideal from an efficiency or debuggability perspective.

Questions:
- how to make continuations and controllers available to such functions?
- how to ensure type-safety?

One option is Quasar integration: #41

**Comment by abreslav** [comment]
Oddly enough, it may give us some form of TCE, see [this paper](http://i.cs.hku.hk/~bruno/papers/APLAS2015.pdf)

**Comment by abreslav** [comment]
Having "coroutine-transparent" functions is close to what Quasar does with `@Suspendable` methods.
Quasar does it through bookkeeping involves ThreadLocals, AFAIK.

Other options (for limited scope) could be:
- implicitly passing extra parameters;
- using fields of the current object (then, only methods of the same class and its nested classes/lambdas can be transparent, and not extensions defined in a different file, for example).

**Comment by elizarov** [comment]
With revised implementation in 1.1-M04 (when controllers were ditched) this is no longer an issue. The topic-starting code just works as expected.
