### ISSUE TITLE
Use case: exit-early computation (akin to Maybe monad)

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#37]
Description:
- When a value in the middle of computation evaluates to null, terminate the computation and return the default value

NOTE: The same may be achieved through exceptions

Similar cases:
- Retry on null

Issues:
- Properties as suspension points (#24)

``` kotlin
val e = maybe(default = 5) {
    // would like to do .mb, but have to do .mb() instead
    val x = foo?.bar().mb()
    val y = x.baz.mb()
    x + y
}
```

Library:

``` kotlin
fun <T : Any> maybe(default: T, coroutine c: () -> Coroutine<MaybeController<T>>): T? {
    val ctl = MaybeController<T>()
    c().entryPoint(ctl).resume(Unit)
    return ctl.result ?: default
}

class MaybeController<T : Any> {
    var result: T? = null

    suspend fun <V: Any> V?.mb(c: Continuation<V>) {
        if (this == null) return // TODO: execute finally blocks here
        c.resume(this)
    }

    operator fun handleResult(v: T) {
        result = v
    }
}
```

**Comment by elizarov** [comment]
Is it really a use-case for coroutines? It is natively handled by exceptions. You can implement it extremely efficiently with exceptions. Coroutine-based implementation will unlikely to ever be as efficient. See the following that properly supports all kinds of try-finally blocks (including catch-exception-rethrow style finally blocks) and defines `mb` as extension property:

```
private val ABORT = Throwable("Abort")

public val <V: Any> V?.mb: V get() = this ?: throw ABORT

public fun <T: Any> maybe(default: T, block: () -> T): T {
    try {
        return block()
    } catch (t: Throwable) {
        if (t == ABORT) return default
        throw t
    }
}
```

**Comment by elizarov** [comment]
Closed. Obsolete. (actually `Arrow` has it now on top of coroutines, I think)
