### ISSUE TITLE
Feedback, use cases, and request

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlin-coroutines#38]
First of all: thank you very much for all your awesome work.
It was a very nice surprise that you were working on suspendable functions already,
and even trying for Kotlin 1.1.

I just wanted to provide feedback, about my experience with await/async. I did sometime ago on the forums.
But maybe now I can provide more information, including our current use cases, and my own experience with this kind of stuff.

**Introduction:**

I first used await/async when C# came with it, after some time considering that fibers/green threads were the way to go.

Lots of years before I used DIV and DIV like programming languages (process oriented for games) that used suspendable fibers in order to achive concurrency: each process/entity executed some code until a FRAME statement reached, and the function was suspended. That was great because the machine state is implicit and it is really a pleasure to read and to understand what's going on.

**Fibers:**

Fibers/Green thread require support for the operating system / high level language or at least having raw access to assembly.
You have to have a stack per green thread (and handle growing of the stack or having a trade off between memory and execution capabilities), and also you have to backup all your registers and restore them, and of course handling exception handling/traps whose information is usually stored in the stack and some information before the forking.

So even when stacks of green threads tend to be smaller than full thread stacks, it's not completely efficient: http://www.kegel.com/c10k.html

So even when your execution process is very small you have to have a stack.

**Await/Async:**

Await/async/yield works different. Instead of using the stack and requiring support for it, it can work everywhere. A simplification of the process:
- Function is transformed into a generator + a struct/class with the state + a function that can be called several times specifying the state
- So usually a function with a reductible CFG is transformed into a function with a switch matching the current state position at the very beggining with gotos and local variables are transformed into access to fields in the state structure.
- And each await, changes that state position to the next one, and registers the specified promise/task/future to call itself, and just after returns the function. So when the awaitable is completed, it will execute itself but will jump to the next state position.

I created a project that does this process here with bytecode instrumentation:
https://github.com/soywiz/jawaitasync

My experience with it:
I had several issues. For example jvm has an opcode to create an instance of an object, but that object is uninitializated before invokespecial <init> and in some cases I had suspension points having the stack with uninitialized objects (that would have been easier if they called the construction in just one opcode or the object/arguments had the reverse order to avoid that nasty DUP :)).
Before the suspension I had to store the stack into synthetic locals that were actually fields in the state structure, so I could restore it later.
I stopped it because I didn't like Java and Scala was not what we were looking for and experimented with other stuff (including typescript and haxe), until I found Kotlin! Then expected this moment to happen.

Since in kotlin you have a proper AST, it should be easier to avoid the problems I had with bytecode intrumentation.

Before typescript had await/async I implemented it using generators:
https://github.com/soywiz/tspromise/blob/master/Promise.ts#L157

So in the case you have bidirectional generators (python or javascript ones), you can separate the await/async logic from that. C# for example had unidirectional generators (it can emit values, but not retrieve values after resuming the function), so it was not easy to emulate await/async with generators.

**Our use cases**

We are using right now kotlin jvm in both backend and frontend.

We have a common "promises/thenable" implementation that is used in both, frontend and backend. In fact, futhermore to thenable, it has pipeing and other useful stuff, that wouldn't be required after async/await is implemented.
In the backend we are using vert.x as single threaded eventloop, and we have all the IO asynchronous; lock free. And we are scaling adding more nodes, just like nodejs works.

In the frontend we are using: https://github.com/jtransc/jtransc/ (which is my current project that I have been working on in the last months). It works already and we have games that are compiled into javascript, flash and C++ for both android and ios. Since it uses bytecode we can have mixed code: kotlin + java libraries.
And because jtransc aims to target several stuff including javascript and flash, it doesn't implement threads at all.
In the frontend part we have an eventloop too, js and flash use their own and in C++ it is emulated.

**Futures/Tasks/Threads/Promises/Thenables : Proposals/requests**

I have seen that the current implementation uses CompletableFuture.

The main problem of java Futures is that they can block the thread waiting for a value and its API is pretty complex. And thenable are simle and hell and promises makes that impossible, they are completely reactive and don't even allow to determine wheter a promise is completed or not which is great to avoid bad code.

So it would be great if the implementation works with our custom promise implementation.

If Kotlin would have some kind interfaces (like typescript or typedefs in haxe or scala) that wouldn't require to be implemented explicitly but enforced at compile time, it would be pretty easy to add just a thenable/continuable contract that would work. I know that it is costly at runtime because of the reflection or would require invokedynamic stuff.

Other possible stuff would be if Kotlin provides a proper interface that we could implement (that would be enough for use). But it wouldn't work with java Futures. Though you could check if it is a Future to call a method or if it implements the interface to call the other.

https://github.com/Kotlin/kotlin-coroutines/blob/master/examples/async.kt#L43
Other thing that could work would be instead separating the suspension from the await/async executor (the one that knows about Promises/Futures and stuff), to embed calling in the suspendable function. That way you can determine at compile time which method to call (.then, .whenComplete or other) without any kind of overhead. But I know that this approach would couple stuff and make stuff more complicated, and being able to separate is a design goal as far as I read.

I think that a small overhead (instanceof) is not a problem, since most asynchronous programming is pretty simple. Most of the time the process is idle waiting for IO / or tweening / waiting other kind of events.

So my request here is to support some kind of thenable without involving java's futures at all.

**Comment by abreslav** [comment]
> Since in kotlin you have a proper AST, it should be easier to avoid the problems I had with bytecode intrumentation.

While we are aware of [the issues you've mentioned](https://github.com/Kotlin/kotlin-coroutines/issues/14), we believe (and partly from the experience of the C# team) that implementing this through bytecode transformation is way easier than through AST.

> Before typescript had await/async I implemented it using generators:
https://github.com/soywiz/tspromise/blob/master/Promise.ts#L157

> So in the case you have bidirectional generators (python or javascript ones), you can separate the await/async logic from that. C# for example had unidirectional generators (it can emit values, but not retrieve values after resuming the function), so it was not easy to emulate await/async with generators.

Since I can't check this too quickly: is your solution type-safe? Or does it rely on the untyped JS?

> I have seen that the current implementation uses CompletableFuture.

It's only an example

> So it would be great if the implementation works with our custom promise implementation.

Coroutines are designed specifically for this purpose: supporting different kinds of APIs equally well. Please check [the proposal document](https://github.com/Kotlin/kotlin-coroutines).

**Comment by soywiz** [comment]
With the AST I meant that while generating the bytecode from the AST, you can handle how to generate some stuff to avoid some kind of problems. Indeed with tons of high level structures I understand that it would be incredibly complicated as a AST transformation. And probably the only sane way would be simulating labels through switch/cases which would be the same as generating the bytecode.

----

The typescript micro-library was "type-safe", all the type-safe typescript can be (promises were handling and returning typed values and enforced at compile-time). But you can always do strange stuff with "any" (the equivalent to dynamic in kotlin.js), and you can cast stuff wrong.

But allowed some signatures (supported by plain ES6 promises) that can't be supported on java because collisions:
```
then<TR>(onFulfilled: (value: T) => Promise<TR>, onRejected?: (error: Error) => TR): Promise<TR>;
then<TR>(onFulfilled: (value: T) => TR, onRejected?: (error: Error) => void): Promise<TR>;
```
In java/kotlin we have two different methods, the second one called `then` and other called `pipe`.

Though when using with await/async `pipe` is not necessary anymore, just a plain `then`.

I wrote that micro-library a couple of years ago, and it has been superseded. Now promises are mainstream, ES6 is almost on all browsers including generators, and typescript supports await/async already using generators when targeting to ES6 and ES7 is going to include it.

----

Shame on me! I missed the cool document :) I will read it. I'm really eager to understand how it is going to be designed to work with all the stuff and handled by the library (potentially other libraries?) and being async a keyword over there already!

I will write again after I read the document if I have some related feedback about it.

**Comment by soywiz** [comment]
Readed it. Simply awesome. I really like your approach.

I though that being `async` already reserved in some contexts it was not going to be a plain function and was going to be handled other way. But probably you will just remove that context-keyword when this is out or enforcing that it is a function.

So as far as I understand, the only thing I will have to do is to create the async function for my Promises. And in the case there are several async functions available, I will have to chose which one to import.
And it won't be able to determine which one to use (probably same descriptor), so in the case I have conflicts using libraries, I would have to use typealiases or fqnames to reach the right function. Though in our use case we won't have conflicts because we just use one Promise implementation.

So the only thing I have to add is that I want to use it right now :) 👍

**Comment by abreslav** [comment]
> But probably you will just remove that context-keyword when this is out or enforcing that it is a function.

Yes, we will remove this restriction.

> And it won't be able to determine which one to use (probably same descriptor), so in the case I have conflicts using libraries, I would have to use typealiases or fqnames to reach the right function. 

As an option, you can use `import a.b.c as d`

**Comment by elizarov** [comment]
Closed. Obsolete. Thanks everybody for feedback.
