### ISSUE TITLE
Restrictions on suspension points inside try blocks

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#4]
Should we allow suspension points inside `try` block that have a `catch`?

C# outlaws it, here's why: https://blogs.msdn.microsoft.com/ericlippert/2009/07/23/iterator-blocks-part-five-push-vs-pull/

**Comment by abreslav** [comment]
Relates to #9 and #11

**Comment by abreslav** [comment]
Relates to #10

**Comment by elizarov** [comment]
We don't have any restrictions on suspension points and it covers all the use-cases that we have.
