### ISSUE TITLE
Allow varargs in suspension functions ?

### ISSUE THREAD

**Issue by SalomonBrys** [Kotlin/kotlin-coroutines#42]
Why are suspension functions not allowed varargs parameter ?

If the continuation parameter was the *first* parameter instead of being the *last* one, it should be possible, so I'm guessing there's another reason for this limitation.

**Comment by abreslav** [comment]
The document says:

> the last of its parameters (the continuation parameter) is not vararg, and

Which doesn't mean that varargs are not allowed at all :)

In fact, we allow varargs in the position before last in other parts of the language, so it should be alright here, too. I'll add a clarification to the document.

**Comment by SalomonBrys** [comment]
Sorry for the misunderstanding ;)
