### ISSUE TITLE
Do we actually need the Coroutine interface?

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#45]
In most examples builder functions do something like `c().entryPoint(controller)` where `c` is coroutine-marked parameter.
For me it seems much more natural to pass controller just as common argument or extension receiver when invoking coroutine lambda.

```
fun <T> async(coroutine c: FutureController<T>.() -> Continuation<Unit>): Future<T> {
 val firstContinuation = controller.c() // or may be c(controller)
 ...
}
```

**Pros**
* API reduction
* It looks more clearly than `fun <T> async(coroutine c: () -> Coroutine<FutureController<T>>): Future<T>` where we have two words coroutine in different contexts

**Cons**
* We add more strict conditions on corotine functional type shape (it should have controller as extension receiver or parameter)

See also #44

**Comment by abreslav** [comment]
After considering carefully: no, having the Coroutine interface doesn't sound like such a good idea. We'll go for the simpler version
