### ISSUE TITLE
Inline suspend functions with inline lambdas

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#48]
I think that inline suspend functions should be allowed in general, but their value parameters of functional types should be `noinline` or `crossinline`, i.e. no local returns/suspension calls will be allowed within corresponding lambda (see #47).

```
class Controller {
    inline suspend fun await(block: () -> Unit, x: Continuation<Unit>) {
        block()
        x.resume(Unit)
    }
}

fun test() {
    builder {
        await {
            // here suspension happens within suspension call
            await {
                print("")
            }
        }
    }
}
```

The main problem here is that suspension calls inside of suspend functions may be rather counterintuitive

**Comment by abreslav** [comment]
As an exercise, let's try to imagine what such a "nested" suspending call could mean.

First, what does an inline suspension function mean? It means that its body is inserted right before a `return` instruction in the `doResume` method. 

If a lambda is inlined in the middle of that body, it will result in another suspending call inserted between setting the `label` variable for the first suspending call and returning from `doResume`. I.e., there will be another assignment to the `label` variable (+ maybe stack spilling etc), and to resume correctly from such a suspension, , would we need a stack-like structure for the information saved before suspension. 

Outline:

- outer suspending call:
  - compute whatever must be on stack before the suspension
  - save it to fields
  - save relevant variables to fields
  - assign the `label`
  - execute some inlined code
  - inner suspending call:
    - compute whatever must be on stack
    - save it to fields (more fields? or can we overwrite?)
    - save relevant variables to fields ( - " - )
    - assign the `label` (previous value is lost)
    

Can't say I understand the possible semantics of all this ATM... Confusing indeed

**Comment by abreslav** [comment]
Alternative option to consider:

- instead of prohibiting `inilne` lambda parameters to suspending functions, prohibit suspension calls in lambdas passed to suspending sunctions

**Comment by dzharkov** [comment]
I think non-local returns in the middle of suspension may be confusing either, thus requiring `crossinline` for such lambda looks reasonable to me

**Comment by elizarov** [comment]
*Update*: This is still an issue in Kotlin 1.1: https://youtrack.jetbrains.com/issue/KT-16603

**Comment by elizarov** [comment]
Closed. Fixed.
