### ISSUE TITLE
Builder functions with inline coroutine parameters

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#49]
It seems impossible to implement coroutines in such a way to allow non-local returns from coroutine lambdas, because their code is encapsulated within real `Continuation` object and could not be inlined.

```
class Controller 
inline fun builder(coroutine x: Controller.() -> Continuation<Unit>) {}

fun test() {
    builder {
        // non-local return
        return@test
    }
}
```

The possible solutions are:
- treat `coroutine` parameter as `crossinline` (in case of inline functon)
- prohibit `coroutine` but not `crossinline` parameter for inline function

**Comment by abreslav** [comment]
I'm strongly for the first option: imply that `coroutine` is always `crossinline`

**Comment by abreslav** [comment]
But let's not forget that we have a third option: 

- reject `inline` builder functions.

Seems too restrictive though

**Comment by elizarov** [comment]
It seems to be related to https://youtrack.jetbrains.com/issue/KT-16603. In addition to coroutine builders with `inline suspend` parameters, there are also use-case for `inline suspend` scoping functions with `inline suspend` parameters.

**Comment by elizarov** [comment]
The one remaining issue is support for `cross inline` on suspend functions https://youtrack.jetbrains.com/issue/KT-19159

**Comment by elizarov** [comment]
Closed. Fixed.
