### ISSUE TITLE
Suspension points within `synchronized`

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#50]
The problem is that `synchronized` is a common inline function and suspension points are allowed in corresponding inline lambda according to #47.

At the same time I can see no way to implement suspension having monitor being locked   

```
class A {
    fun test(future: CompletableFuture<String>) {
        async {
            synchronized(this@A) {
                // suspension point with monitor being locked
                await(string)
            }
        }
    }
}
```

**Possible solutions:**
- The obvious solution, namely, rejecting suspension points exactly for `synchronized`, doesn't work because it can be inlined into another inline functions.
- Another solution is to determine such problems while generating coroutine bytecode and report them after (AFAIK the same idea is used for cycles detection between inline functions)

**Comment by abreslav** [comment]
Note: if we do nothing and simply allow this, the code will break at runtime with a `VerifyError` or something similar.

**Comment by abreslav** [comment]
I'd go for the second option: checking the byte code after-the-fact

**Comment by elizarov** [comment]
The problem with bytecode checking solution is that it is very _ad-hock_. It addresses only the problem of `synchronised` stdlib function, but it does not solve the problem for all the similar utility functions that are/will be defined in user code. For example, consider the following helpful utility for working with `java.util.concurrent.Lock` objects: 

```
inline fun <T> withLock(lock: Lock, block: () -> T): T {
    lock.lock()
    try {
        return block()
    } finally {
        lock.unlock()
    }
}
```

We want it to be `inline`, but it suffers from the same problem as `synchronised`, because it is not prepared to be suspended and then resumed in some other thread.

The functions like this are rare, though. So, a more _general_ solution is to introduce some kind of `nosuspend` modifier or annotation for functional parameters of inline functions.

**Comment by storozhukBM** [comment]
> The functions like this are rare

In Java I'm using such functions to encapsulate StampedLock usage madness into few concise methods like that:
```java
private <T> T readConcurrently(final Supplier<T> readSupplier) {
        T result;
        long stamp;
        for (int i = 0; i < RETRIES; i++) {
            stamp = stampedLock.tryOptimisticRead();
            result = readSupplier.get();
            if (stampedLock.validate(stamp)) {
                return result;
            }
        }
        stamp = stampedLock.readLock();
        try {
            result = readSupplier.get();
        } finally {
            stampedLock.unlockRead(stamp);
        }
        return result;
    }

private <T> T writeConcurrently(final Supplier<T> writeSupplier) {
        T result;
        long stamp = stampedLock.writeLock();
        try {
            result = writeSupplier.get();
        } finally {
            stampedLock.unlockWrite(stamp);
        }
        return result;
    }
```
And I'm pretty sure that such usage scenarios aren't rare.
Dr. Heinz M. Kabutz have mentioned similar usage of lambdas here http://www.javaspecialists.eu/archive/Issue215.html

**Comment by abreslav** [comment]
@elizarov The problem with nosuspend is that it will affect a lot of code that doesn't care about coroutines at all. OTOH, detecting try-finally in the byte code is a reliable check, but nothing helps library authors to know whether adding a try-finally to an existing function breaks some clients or not.

**Comment by elizarov** [comment]
`nosuspend` should not replace bytecode checks. We should check bytecode. It is not hard for us, but it will help catch bugs in the other people's code. 

However, by only implementing bytecode checks we don't give our library/DSL writers any way to say "hey, I want this block to be inline, but I know that if somebody suspends there, he's going to run into a problem". The downside of `nosuspend` is that it becomes a "viral" modifier for inline lambda blocks, just like `suspend` itself and there's no easy way to work around that (this is a common problem to all effect-like language type-system mechanisms).

**Comment by elizarov** [comment]
I've also created https://youtrack.jetbrains.com/issue/KT-17260 to track this issue and it is becoming stumbled upon by the users of Kotlin coroutines.

**Comment by elizarov** [comment]
Closed, fixed. Suspension inside synchronized is not allowed.
