### ISSUE TITLE
Prohibit handleResult/handleException extensions to controller

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#51]
I think it's worth to prohibit them at least for now.
My main point is that in case they're allowed it may lead to implicit behavior changes.
For example resulting execution may depend on import presence

**Comment by rocoty** [comment]
Extension functions are statically resolved, and actual functions in the object take precedence. I don't see the problem here.

**Comment by dzharkov** [comment]
The problem is that their presence or absence may affect the behavior implicitly.
It's been decided to prohibit them at least for now.
