### ISSUE TITLE
Should suspend constructors be allowed?

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#52]
I can see no obvious reasons why they should be prohibited.
Potential use-case is constructor of future-like object that use a continuation within itself

**Comment by elizarov** [comment]
Suspending constructors will definitely require some extra backend works, but are indeed very useful. The support of suspending constructions would enable to use suspending functions in init block and in property initialiser. The code-generation strategy for suspending constructors is tricky. A synthetic non-arg constructor will have to be generated and the constructor code itself must be transformed into suspneding factory method that creates this non-itialized object, calls all the (potentially suspneding) initialisation code and returns the resulting object via continuation. All invokers of suspending constructor will have to call the corresponding static factory method instead.

**Comment by elizarov** [comment]
*Update:* This is still an open issue as on Kotlin 1.1. Support for suspending constructors in future version is TBD.

**Comment by ochalouhi** [comment]
How about suspending property getters / setters , or suspending delegation ?

**Comment by sanity** [comment]
Just wanted to check in on @ochalouhi's last question, I also have a usecase for this.

**Comment by mishaxz** [comment]
I need to call a suspend fun in the init block (meaning code would be cleaner than working around it), so this would be nice

**Comment by elizarov** [comment]
Suspending `init` blocks (and suspending constructors) are unlikely to be supported in the near future. You always have an option of defining a factory function (aka pseudo-constructor) manually, though.

**Comment by finchatticus** [comment]
@elizarov could you show example "of defining a factory function (aka pseudo-constructor) "?

**Comment by elizarov** [comment]
Suppose you want to write something like:

```
class Foo {
    val data = loadDataFromServer() // suspending function
}
```

So, you want to perform some asynchronous operation while construction a class. You can always rewrite it like this:

```
class Foo(val data: Data) // regular constructor that accepts the data

// pseudo-constructor suspending function
suspend fun Foo() = Foo(loadDataFromServer())
```

**Comment by LouisCAD** [comment]
Here's an example `abstract class` that can be inherited by a `companion object` and bring a `suspend` constructor like method to the class owning the `companion object`: https://github.com/LouisCAD/Splitties/blob/beb45da8ede57383aec489ac9d5630e79db60cc9/preferences/src/main/java/splitties/preferences/experimental/SuspendPrefsAccessor.kt#L29-49

**Comment by elizarov** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-27703
