### ISSUE TITLE
[feedback] A weekend with coroutines

### ISSUE THREAD

**Issue by soywiz** [Kotlin/kotlin-coroutines#53]
After a weekend experimenting with kotlin 1.1 (mostly porting this: https://github.com/soywiz/NodeNetAsync/ ) coroutines from git, I have some feedback.

First of all. This all is simply awesome. Not just well designed, but was live so fast! .NET take lot of time and this has lots of edge cases. So great job :+1: 
## Bugs/Problems

So far I have found an invalid code generation and it was not related to double/longs which I hate so much, and probably you too, when working with bytecode :). I have reported it already: https://youtrack.jetbrains.com/issue/KT-12958
Example here and how I circumvented it for now: https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/es/kotlin/db/async/redis/RedisClient.kt#L58

Other problem I found is that there is no compile-time or runtime exception when no suitable handleResult is found. So this failed silently and that's a problem:
https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/es/kotlin/db/async/redis/RedisClient.kt#L91

One more problem. An IllegalAccess which should have been reported at compile-time or directly work (not sure if this is bad code generation or just no error):
https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/es/kotlin/vfs/async/VfsFile.kt#L77
## Questions

Will be possible to support the AsyncStream pattern just with plain fors? Doesn't have a suggestion here. But would be useful here and here:
https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/es/kotlin/vfs/async/VfsFile.kt#L77
https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/example-async-generator.kt#L8
## Suggestions

I found that it would be awesome to do stuff like this:

https://github.com/kotlin-es/coroutine-examples/blob/e07570fdcd4dabfd60f3d16941a602d4f6d3aa54/src/es/kotlin/vfs/async/VfsFile.kt#L12

Extension suspend functions but not in the controller itself, but outside as plugins.
An extension of a Type, for a controller (a double extension?? :P )
For example I have a `async` + controller, but I have a module to handle Vfs and that controller shouldn't know about Vfs stuff at all. But Vfs would define some extension methods to simplify working with async code in async blocks.

**Comment by dzharkov** [comment]
Thank you for such a detailed feedback!

All problems you've found are bugs indeed:
https://youtrack.jetbrains.com/issue/KT-12969
https://youtrack.jetbrains.com/issue/KT-12974

I didn't get what you meant by `AsyncStream` pattern, could you give a short example, how should it look like?

Suspend extensions probably will be supported in the very near future (double extensions are unlikely), feel free to vote or to add your example to the issue https://github.com/Kotlin/kotlin-coroutines/issues/7

**Comment by soywiz** [comment]
Cool :)

----

AsyncStream is like Iterator but asynchronous. So in Dart (that have Future(Promise) + Stream) you can do this:
https://www.dartlang.org/docs/tutorials/streams/#receiving-stream-events

I don't know whether .NET already supports this, because I switched sometime ago. But the idea is to lazily and asynchronously iterate/consume over something that is produced asynchronously too.
For example a resultset in a database of million of rows. You don't want to generate a list, of it: just produce rows, and consume them one by one. The same goes with reading a 1TB file. You may want to pipe it to a file, transferring small chunks to avoid wasting too much memory. That's the use of the Stream concept.

They allow to consume it in the same coroutine. I tried to do a lambda, but triggered [KT-12974](https://youtrack.jetbrains.com/issue/KT-12974) so couldn't test it. Not sure how practical would be to work with lambdas in that case or which overhead could introduce. So that's what I asked.

---

Regarding to extensions part: I think that one cool think about extension methods is that you can write from left to right. You type your subject and then you write its transformations until the final result is achieved. Easy to write, easy to read. Also extension methods allows to discover, what you can do with your subject, instead of having to know that there is a static class or a public method doing this or that.

So I want for example to, inside an async block, to have an extension method for the VfsFile, creating a `.stat()` extension method instead of having to write `.statAsync().await()`. But since it is a continuation I want to be available just inside the async block. But don't want to write `stat(file)`. Because `stat` concept is intrinsic to the VfsFile class and no other class.

So maybe not the "double extension" syntax, but something that allows to do that would be awesome.

---

Other thing that I missed is that I though that suspension calls would be colored differently. I didn't mentioned it because I know that probably it will be included in the future. But I think totally worth it :)

---

Right now I'm porting a Mysql Client I did for .NET with await/async. That's much more complex that the redis client, so if I find more bugs I will report them!

**Comment by elizarov** [comment]
Were you previous problems addresses by the revised coroutines implementation? Can we close this issue?

**Comment by soywiz** [comment]
Totally :) You did an extremely good job here!
