### ISSUE TITLE
Use case: "Swarm"

### ISSUE THREAD

**Issue by sanity** [Kotlin/kotlin-coroutines#58]
I wanted to describe an interesting use-case for coroutines, provided that they support serialization of the continuation (which seems to be the case based on a few mentions in the docs).

"Swarm" is a proposal for an approach to distributed computation based on the idea of "move the computation, not the data".  While map-reduce employs a similar philosophy, it is rather constrained.  Swarm will generalize this idea to allow almost any type of computation to be distributed automatically across multiple computers.

The idea is that data is stored as an object graph (much as in a normal JVM), however this object graph is distributed over multiple computers, and the objects can reference objects on remote computers.

A thread runs and operates on this object graph as normal, until it attempts to dereference an object on a remote machine.  At this point, the thread is frozen, serialized, sent across the network to this remote machine, deserialized, and it resumes, all transparently to the programmer.

Of course, jumping between machines is a very expensive operation relatively speaking, and so we employ a separate supervisor process to monitor how objects are being accessed, and attempt to arrange data that tends to be accessed together on the same machine, employing a clustering algorithm.

In doing so, algorithms can be implemented in a much more flexible way than map-reduce, and thanks to the clustering algorithm, if there is a way to distribute this computation efficiently, Swarm will do it.

Sharing CPU and storage across multiple machines isn't the only application for this idea.  For example, in theory it could break down the barrier between code running in a web browser and code running on a server, allowing a programmer to modify the browser's DOM in one line, and then immediately access a database on the server on the very next line of code.  The programmer can focus on what their code is doing, rather than having to architect everything around a client-server divide.

I don't know if Kotlin's JavaScript compiler will be interoperable with Java such that you could transfer a continuation between them, and it would also be necessary to deal with the fact that a browser is an untrusted execution environment.

Swarm has a rudimentary working prototype implemented in Scala using Scala's "delimited continuations" plugin, but this has been deprecated, and I much prefer Kotlin over Scala anyway.

Much more here (including the rudimentary Scala prototype): http://swarmframework.org/

**Comment by elizarov** [comment]
Kotin coroutines are conceptually similar to Scala's delimited continuations, so the Swarm implementation should be readily portable to Kotlin. Here is a correspondence between the corresponding Scala and Kotlin's primitives:
* `reset` corresponds to `startCoroutine` in Kotlin
* `shift` corresponds to `suspendCoroutine` in Kotlin

**Comment by sanity** [comment]
@elizarov Yes, I think the main question was the serializability of the coroutine, am I correct in believing that coroutines are now serializable?

**Comment by elizarov** [comment]
Kotlin coroutines have been serializable since inception (in previous revision, too) in the same way as Scala's delimited continuations are, so I don't see any migration barrier here.

**Comment by sanity** [comment]
Thank you.  It took me a while to get my head around shift/reset back when I did the original Swarm prototype a few years ago in Scala.  Many braincells have died since then but I'm going to dig into this today and try to refresh my memory.

Thank you for your help @elizarov
