### ISSUE TITLE
Storing local variables of a coroutine

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#6]
Options
- copy variables to fields at suspension points only (easier debugging experience)
- store all variables shared between states in fields all the time (may be faster)

**Comment by fvasco** [comment]
Store all variables may lead to memory leaks, a variable can remain referenced but never more used in later states.
The compiler should add some set to `null` for each unused variable: after the last occurrence in coroutines.

**Comment by elizarov** [comment]
Closed. Obsolete.
