### ISSUE TITLE
Make sure that support for cancellation is possible

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#60]
Canceling asynchronous tasks is very important, for example, in UI applications. We may need to extend the `Coroutine` API for this, or maybe the present minimal API works alright, but we need to make sure that cancellation can be implemented.

See https://jeremybytes.blogspot.ru/2015/01/task-and-await-basic-cancellation.html for .NET-related description

Reported by @korifey

**Comment by elizarov** [comment]
Cancellation is supported. See https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md
