### ISSUE TITLE
Performance: sequence operations implemented with coroutines are ~2 times slower

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlin-coroutines#63]
I've [implemented](https://github.com/ilya-g/kotlinx.collections.experimental/blob/master/kotlinx-collections-experimental/src/main/kotlin/kotlinx.collections.experimental/sequences/operations.kt#L3) some standard sequence operations like `map` and `filter` with the `generate` coroutine and [benchmarked](https://github.com/ilya-g/kotlinx.collections.experimental/blob/master/kotlinx-collections-experimental/benchmarks/src/main/kotlin/sequences/SequenceCoroutineOperations.kt) them against standard hand-written sequence implementations.

The [results](https://github.com/ilya-g/kotlinx.collections.experimental/blob/master/kotlinx-collections-experimental/benchmarks/src/main/kotlin/sequences/results.txt) show that the operations implemented with coroutines perform approximately 2 times slower than hand-written ones.

We have made perfasm dumps of the hottest code regions both for [C2](https://github.com/ilya-g/kotlinx.collections.experimental/blob/master/kotlinx-collections-experimental/benchmarks/src/main/kotlin/sequences/jmh.log) and [C1](https://github.com/ilya-g/kotlinx.collections.experimental/blob/master/kotlinx-collections-experimental/benchmarks/src/main/kotlin/sequences/jmh-C1.log) JIT mode, but now we're having a hard time interpreting these dumps.

Definitely the difference comes from the overhead introduced with `generate` controller and the coroutine state-machine, but it's hard to tell which part causes the most overhead.

**Comment by dzharkov** [comment]
On my computer I have similar results:
```
SequenceCoroutineOperations.filter_ai      avgt   40   597.027 ±  3.916  us/op
SequenceCoroutineOperations.filter_c       avgt   40   829.333 ±  3.496  us/op
SequenceCoroutineOperations.filter_ci      avgt   40   763.582 ± 10.388  us/op
SequenceCoroutineOperations.filter_std     avgt   40   612.364 ±  9.044  us/op
SequenceCoroutineOperations.filter_std_ai  avgt   40   680.840 ± 16.615  us/op
SequenceCoroutineOperations.map            avgt   40   835.985 ±  6.347  us/op
SequenceCoroutineOperations.map_c          avgt   40  2164.208 ± 39.578  us/op
SequenceCoroutineOperations.map_ci         avgt   40  2478.191 ± 12.054  us/op
```

But everything gets much better if fields representing coroutine state at suspension point are not volatile:
```
SequenceCoroutineOperations.filter_ai      avgt   40   594.437 ±  2.475  us/op
SequenceCoroutineOperations.filter_c       avgt   40   617.173 ±  5.075  us/op
SequenceCoroutineOperations.filter_ci      avgt   40   547.012 ±  7.807  us/op
SequenceCoroutineOperations.filter_std     avgt   40   601.647 ±  2.240  us/op
SequenceCoroutineOperations.filter_std_ai  avgt   40   667.129 ±  2.321  us/op
SequenceCoroutineOperations.map            avgt   40   826.882 ±  3.949  us/op
SequenceCoroutineOperations.map_c          avgt   40  1306.237 ±  7.419  us/op
SequenceCoroutineOperations.map_ci         avgt   40  1357.939 ± 12.213  us/op
```

The interesting thing is that coroutine based `filter` has just the same results, but `map` is ~ 1.5 slower.
I think the main reason, why stdlib implementation is faster is that - iterators of `TransformingSequence` maintain very simple state (they just call delegating iterator and then apply transformation function),
while coroutine implementation has to store/load continuation state, also it's body contains non-trivial control-flow operations

**Comment by dzharkov** [comment]
Relevant to #63

**Comment by dzharkov** [comment]
Relevant to #17

**Comment by elizarov** [comment]
@ilya-g Can you confirm we are fine now and close this issue, please?

**Comment by ilya-g** [comment]
Currently coroutine-based implementations are only 1.5 time slower than hand-written.

I'm going to investigate performance of various sequence operation implementations later. I'll reopen this issue, if I find something interesting.
