### ISSUE TITLE
Prohibit non-Unit suspend functions

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#64]
From my point of view returning any value from a suspend function is meaningless, because it's anyway will be effectively unused

Also it doesn't work in current implementation ([issue](https://youtrack.jetbrains.com/issue/KT-13560))

Of course it's easy to fix, but IMHO the possibility to declare such a function may be very confusing

**Comment by abreslav** [comment]
I think you are right, and we should prohibit this. Let's add the corresponding change to the proposal

**Comment by dzharkov** [comment]
Already documented

**Comment by dzharkov** [comment]
It's irrelevant since the new convention https://github.com/Kotlin/kotlin-coroutines/issues/71
