### ISSUE TITLE
Multiple handleResult declarations

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#65]
Resolution process for builder-call when controller has the only one `handleResult` is quite straightforward: we treat the call the same way as if builder had signature like `fun builder(c: Controller.() -> HandleResultParameterType)`

```
class Controller {
    operator fun handleResult(x: String, c: Continuation<Nothing>) {

    }
}

// on call site it works like `fun builder(c: Controller.() -> String) {}`
fun builder(coroutine c: Controller.() -> Continuation<Unit>) {}

fun foo() {
    builder { "" }
}
```

But if there are several handleResult's definitions, many questions arise about how inference and candidate applicability algorithm must work.
One of the answers may be to use a union type of all handleResults' parameter types or something similar.

The relevant problem is how resolution works if handleResult itself contains type parameters

**Comment by elizarov** [comment]
This issue is not applicable with a revised convention as there is no more `handleResult`
