### ISSUE TITLE
Should kotlin.coroutines be in the default imports in 1.1+?

### ISSUE THREAD

**Issue by udalov** [Kotlin/kotlin-coroutines#66]
1) Should the compiler add an implicit `import kotlin.coroutines.*` as is done for other packages (`kotlin`, `kotlin.sequences`, `kotlin.jvm`, etc)?
2) If yes, should it be added on all platforms or only on JVM?
3) Also if yes, should the compiler add implicit imports of all classes in the package `kotlin.coroutines`, so that e.g. the name `Continuation` in the source code would resolve to `kotlin.coroutines.Continuation`, even if there's another star import where another `Continuation` could be found? (Note that currently this is happening only for 4 packages: `kotlin`, `kotlin.collections`, `kotlin.ranges`, `kotlin.annotation`.)

**Comment by elizarov** [comment]
The current resolution: NO. It should not.
