### ISSUE TITLE
Does coroutines work with specific thread execution?

### ISSUE THREAD

**Issue by testn** [Kotlin/kotlin-coroutines#68]
I could not find a good example anywhere where the coroutine can handle the thread switching manually. Some framework like Netty requires certain operations to be called from the event loop and switch to the worker thread for blocking operations.

**Comment by elizarov** [comment]
Please take a look at dispatchers in the second revision of coroutines: https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md
Dispatcher installed in a coroutine can check and redispatch execution of the coroutine to another thread after suspension, if needed.
