### ISSUE TITLE
Allow extensions to controller as suspending functions?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#7]
Some controllers can't allow it, e.g. `yield`, but some may benefit from it greatly: e.g. a web framework with many asynchronous services defined in plugins.

**Comment by bsideup** [comment]
I'm building DSL for my framework and I want to make it pluggable. DSL heavily relies on coroutines, and I can't place all suspend methods in one place (because of the pluggable nature), so big +1 from me to make it work, thanks!

**Comment by bsideup** [comment]
Example:

```kotlin
// Core framework
class Execution {
// some coroutine support
}

fun execution(coroutine Execution.() -> Continunation<Unit>) {}
```

Then somewhere in Twitter's plugin
```kotlin
suspend fun Execution.sendToTwitter() {}
```

Then somewhere in Instagram's plugin
```kotlin
suspend fun Execution.sendToInstragram() {}
```

Then is user's DSL:

```kotlin
execution {
   val success = sendToTwitter()

   if(success) {
      sendToInstagram()
   }
}
```

**Comment by abreslav** [comment]
@bsideup Thanks for the use case. 

My current understanding is as follows:

- there are cases where suspension points can not be added as extensions, so there must be a way to prohibit adding them
- there are cases (like yours) where such extensions are desired, so there must be a way to allow adding them

The questions are:
- what should be the default, if any? (the safest would be to have the more restrictive one (no extensions) by default)
- what is the syntax for the non-default case(s)?

**Comment by bsideup** [comment]
@abreslav sorry, somehow I missed your answer.

Right now I'm really missing extensions support because it breaks the whole idea of my DSL (where I use coroutines a lot)

I think, by default extensions should be allowed. They are "the beauty" of Kotlin and disallowing them by default will be weird. However, I realize some cases where they can't be added, so receiver should somehow forbid them, but no idea how to do it, unfortunately.

**Comment by bsideup** [comment]
@abreslav another option to consider - inline non-suspendable functions calling generic suspend function. In that case, my example will look like:

```kotlin
// Core framework
class Execution {
// some coroutine support

    suspend fun <T, R> doAwait(CompletableFuture<T> f, next: Continuation<R>) {
        ...
    }
}

fun execution(coroutine Execution.() -> Continunation<Unit>) {}
```

and then:
```
inline fun Execution.sendToTwitter() = this.doAwait(twitterFuture())
```


In such case Kotlin should inline such functions first and then generate the state machine according to the inlined code

**Comment by cypressious** [comment]
What's the reason, some controller can't allow it? I understand it simply doesn't make sense for some controllers but would it break anything if they were allowed anyway?

**Comment by cypressious** [comment]
Regarding use cases:

I think the most important use case is pluggable `async`/`await`. C# has the `Task` class which ties all the different `async` implementations together. Kotlin could have a common `AsyncController` where different implementations like Rx, Android's `Handler`, etc. could be plugged in.

**Comment by dzharkov** [comment]
It seems reasonable to me to allow suspending extensions if controller class has some special annotation:
```kotlin
@AllowSuspendExtensions
class FutureController<T> { ... }

fun <T> FutureController<T>.sendToTwitter(next: Continuation<Result>) = this.await(twitterFuture(), next)
```

**Comment by dzharkov** [comment]
Also in many cases it will be nice if it's possible to declare functions with two receivers: one of them is normal and may be both explicit or implicit and the other is strictly implicit (for controller)

There are several options how to express it in Kotlin:
* the one that works only for coroutines
```kotlin
@CoroutineController(FutureController::class.java)
suspend fun AsynchronousFileChannel.aRead(
        buf: ByteBuffer,
        position: Long,
        c: Continuation<Int>
) {
    // ...
}
```
Also it doesn't allow to specify type arguments for controller class
* another one is more general
```kotlin
suspend fun <T> AsynchronousFileChannel.aRead(
        @ImplicitReceiver controller: FutureController<T>,
        buf: ByteBuffer,
        position: Long,
        c: Continuation<Int>
) {
    // ...
}
```

Both solutions require significant changes in the resolution algorithm, and probably in other compiler's parts

**Comment by abreslav** [comment]
@dzharkov Another (admittedly ugly) option would be to move the controller over to type arguments of Continuation/Coroutine:

``` kotlin
suspend fun <T> AsyncFileChannel.aRead(
        buf: ByteBuffer, 
        c: Continuation<Int, FutureController<T>>
)
```

This will damage all libraries, but none of their clients

**Comment by dzharkov** [comment]
Seems to be obsolete for non-restricted suspend functions
