### ISSUE TITLE
interceptResume operator in Controller

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/kotlin-coroutines#70]
When writing asynchronous code it's sometimes necessary to have the code between suspension points executed in the dispatch (UI) thread. 

[asyncUI](https://github.com/Kotlin/kotlinx.coroutines/blob/0b6d19a322414520154ca8b2165c2e4a2d18455a/kotlinx-coroutines-async/src/main/kotlin/async.kt#L47) function is implemented to support the case, it wraps each resume* call with `SwingUtilities.invokeLater` call, thus all "user" code is executed in the dispatch thread.

There are two kinds of problems:
* It seems that the majority of implementations of async libraries should somehow support the feature (e.g. on Android there is also the UI thread distinction), and it wouldn't be cool if design forced them to write the same boilerplate for wrapping resume calls.
* There's no obvious way how to force the authors of external suspension functions to wrap the continuation calls too.

The solution is to introduce another operator, `interceptResume` having the signature similar to
```kotlin
operator fun interceptResume(block: () -> Unit): Unit
```

And the compiler compiles coroutine a little bit differently when it meets such an operator.
Particularly, it wraps continuation methods into lambda-argument of `interceptResume`, i.e.
they compiled to something semantically identical to
```kotlin
override fun resume(x: T) = 
    controller.interceptResume { doResume(x) } // where `doResume` is as-is state-machine processing 

override fun resumeWithException(x: Throwable) = 
    controller.interceptResume { doResumeWithException(x) } // where `doResumeWithException` is as-is state-machine processing 
```

**Comment by elizarov** [comment]
Usefulness of this operator is not limited to UI. In back-end enterprise systems one often needs precise control on what specific thread-pool different kinds of operations use, so that resource consumption by various time-consuming requests can be controlled. This `interceptResume` operation can be used to implement `fork` coroutine builder that is similar to `async`, but is used with some an executor as its argument, so that the following code can be written:

```
fork(executor) {
    // coroutine code here
    await(...)
    // resumes in our thread pool again
} 
```

**Comment by dzharkov** [comment]
The question arises, whether this operator is the subject to support in JS backend with its single-threaded environment.

**Comment by elizarov** [comment]
It depends on yet-to-be determined rules to separate asynchronous vs synchronous coroutines and suspension functions. It also depends on whether JS backend is going to provide _stub_ implementations for Thread-like primitives or omit them altogether.

**Comment by elizarov** [comment]
This feature is currently covered by `ContinuationInterceptor` element of `CoroutineContext`
