### ISSUE TITLE
Reusing SafeContinuation

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlin-coroutines#77]
Investigate under which conditions it's possible to reuse a single `SafeContinuation` object created by `suspendCoroutine` .

**Comment by elizarov** [comment]
Most of the cases that use `suspendCoroutine` _and_ are performance sensitive can be optimised via `CoroutineIntrinsics.suspendCoroutineOrReturns` that does not have any overhead. For example, this is the case for `generate`/`yield`.

**Comment by ilya-g** [comment]
Consider a case with async buffered i/o, when most of suspend operations complete immediately, but some of them really suspend.

**Comment by elizarov** [comment]
That's a different problem. If you do not suspend, then you do not invoke `suspendCoroutine` at all, so `SafeContinuation` is not created. It is not a problem in this case.

However, the whole implementation in 1.1 is optimised around suspending functions that almost often suspend. They may choose not suspend, but all the logic is optimised around assumption that they do suspend. You should be worried about the fact that the state machine object was already created and variables were spilled from stack from it even if you do not suspend. That is the overhead for rarely-suspends case. We will need to introduce an alternative code-generation strategy to optimize for the rarely-suspends case.

**Comment by elizarov** [comment]
We cannot reuse safe continuation. Case closed.
