### ISSUE TITLE
Calling suspend functions in non-suspend functions

### ISSUE THREAD

**Issue by stangls** [Kotlin/kotlin-coroutines#79]
I found out, that suspending functions can be passed to non-suspending functions, which of course can not work.
The following code compiles, but throws an exception during runtime.

```kotlin
fun funny(internalYield: KFunction1<@ParameterName(name = "value") Int, Unit>) {
    internalYield(2)
}
generate<Int> {
    funny(this::yield)
}.forEach {}
```

In my opinion, doing things like this should be forbidden by the compiler.
As far as I understand it, passing suspendable functions should be not allowed at all. Or only passing to suspendable functions should be allowed.

**Comment by elizarov** [comment]
It is a bug. https://youtrack.jetbrains.com/issue/KT-15390
In reality, `this::yield` shall have a type of suspending function.

**Comment by stangls** [comment]
So am I correct that current solution of KT-15390 implies, that the following code will not compile anymore?
```kotlin
    generate<Number> {
        (1..10).forEach(this::yield)
    }
```

**Comment by elizarov** [comment]
Yes. In 1.1 you will have to use the second version of this code. This will be fixed in a proper way in some future update. We'll need to work around corner cases around suspending function types and their interactions with type-system before we can fully allow callable references to suspending functions.

**Comment by stangls** [comment]
Ok, if this is planned, then I assume we can consider this issue closed.
Thank you very much.
