### ISSUE TITLE
Naming suspending interfaces

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlin-coroutines#80]
Many existing interfaces and classes can be redefined in a _non-blocking_ way. For example, the current version of [KEEP](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md) has the following example of a _suspending_ version of `Iterator`:

```kotlin
interface AsyncIterator<out T> {
    suspend operator fun hasNext(): Boolean
    suspend operator fun next(): T
}
```

One can also define a suspending variant of [`Lock`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/Lock.html) interface: 

```kotlin
interface Mutex { 
    suspend fun lock()
    fun unlock()
}
```

While sometimes we can come up with a totally alternative name (like suspending `Mutex` vs thread-blocking `Lock`) it only adds confusion. It is much better to have a _systemic_ naming convention. 

Consider, for example, a non-blocking alternative to [`lazy`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy/):

```kotlin
public interface AsyncLazy<out T> {
    public suspend fun value(): T
    public fun isInitialized(): Boolean
}

public fun <T> asyncLazy(initializer: suspend () -> T): AsyncLazy<T>
```

While systemically naming this things as `AsyncXXX` seems pleasing at first sight, it is not entirely satisfactory, because it is not _really_ async in the same sense as people are used to this word in JS/C#/Dart. It does not have any futures or promises in there and thus it can sow confusion among newcomers from those languages. Consider, for example, the following declaration:

```kotlin
val v = asyncLazy { ... blah-blah .. }
```

Now if one _actually_ needs a future that completes when `v` is computed, then one has to write:

```kotlin
val futureV = async { v.value() }
```

So, calling `v` itself as `AsyncXXX` is a misnomer, because to get a future one has to use `async` builder on it. 

Can we come up with better nomenclature?

**Comment by cypressious** [comment]
Here's a thought: What if not `AsyncLazy` is the misnomer but `async {}`?

The term "async" can be interpreted in two ways for languages like JS/C#/Dart

1. Is non-blocking
2. Returns a Futrue/Promise/Task

The reason that the term has both of these meanings is because that it's all the respective implementation is able to do. Kotlin's `suspend` however can do more.

Naming something "async" in Kotlin also implies that it is non-blocking but it doesn't imply that it returns a Future (or anything at all). So maybe a method that does return a `Future` should be called `asyncFuture {}` instead?

**Comment by elizarov** [comment]
Interesting idea. What is nomenclature for coroutine builder is updated in the following way:
* `async` just starts a new coroutine like a `go` keyword in Go language (does not have any result type). Available on all platforms.
* `asyncFuture` starts coroutine and returns a `CompletableFuture` (will be cancellable, too!). Available on JDK8+
* `asyncFlow` starts a coroutine and returns Java 9 `Flow` (yields a sequenece of results). Available on JDK9+
* `asyncRxSingle` starts a coroutine a returns `rx.Single` (emits one result). Available for RxJava 2+, can be also provide for RxJava 1.x with the same name, but `rx.Observable` as result.
* `asyncRxGenerate` starts a coroutine and returns `rx.Observable` (yields a sequence of results). Available for RxJava 1+
etc...
It is easy to provide similar builder for project reactor and other things.. The question here is the overall _nomenclature_.

**Comment by cypressious** [comment]
@elizarov I like it

**Comment by elizarov** [comment]
We've decided to go with shorter names for now. They don't have "Async" in the class names, but are mostly designed to represent the business domain, instead of of stressing out asynchronous nature of it.
