### ISSUE TITLE
vertx

### ISSUE THREAD

**Issue by theiceguy** [Kotlin/kotlin-coroutines#83]
Would be really nice to have some coroutine examples which wrap vertx generically.

**Comment by elizarov** [comment]
There is an example in this section in the updated document: https://github.com/Kotlin/kotlin-coroutines/blob/revision-3/kotlin-coroutines-informal.md#wrapping-callbacks
Is that what you were looking for?

**Comment by vietj** [comment]
@theiceguy I've scratched this last summer but it's not up to date anymore https://github.com/vietj/kotlin-coroutines (I'm reachable also on #vertx on the KT Slack)

**Comment by theiceguy** [comment]
I saw the wrapping callbacks section, guess I'll need to create my own wrappers, thanks guys.

**Comment by theiceguy** [comment]
@elizarov, btw, your implementation is AWESOME!  I've been dying for this in the JVM for ages.
