### ISSUE TITLE
mixed java/kotlin project w/ maven

### ISSUE THREAD

**Issue by unicomp21** [Kotlin/kotlin-coroutines#85]
I'm having trouble getting coroutines to work in a mixed project.  Is there a sample project somewhere?

**Comment by elizarov** [comment]
Please, try with Kotlin 1.1 release (there is 1.1.1). Do you still have this issue?

**Comment by vicboma1** [comment]
@unicomp21 in this url 
https://github.com/vicboma1/GameBoyEmulatorEnvironment/blob/master/pom.xml
You have a maven configuration to use coroutines with kotlin & java8

Regards!!
