### ISSUE TITLE
Allow suspension points in `finally` blocks?

### ISSUE THREAD

**Issue by abreslav** [Kotlin/kotlin-coroutines#9]
Implementing suspension points in `finally` blocks may be very tricky, but it looks like C# users wanted this feature very much

**Comment by bsideup** [comment]
Right now main "selling point" for coroutines is "write async code as sync", but without proper control flow (i.e. try {} catch {} finally {}) it's not true anymore. Example:

```
try {
   await doSomething();
} finally {
   cleanup();
}
```

Without "finally" block, one can do something like:

```
var ex : Throwable? = null
try {
   await doSomething();
} catch(e: Throwable) {
   ex = e
}

cleanup();
if (ex) throw ex;
```

But it's flaky, plus might not work in some cases. Also, things get worse in case of nesting. I expect the compiler to do such boilerplate for me, the same as `finally` block in my usual code.

**Comment by dzharkov** [comment]
As far as I understand initial point was not about tricky implementation but about problems that arise with Disposable iterators (#10).
More precisely it's about `yield` expressions in finally block that should be executed after iteration unexpectedly stopped. Next value is generated, but nobody needs it anymore.
There a lot of questions like whether controller should continue `finally` blocks execution if suspension happens at the moment.

Some similar more points are described in the articles on the `yield` design in C#:
* https://blogs.msdn.microsoft.com/ericlippert/2009/07/16/iterator-blocks-part-three-why-no-yield-in-finally/
* https://blogs.msdn.microsoft.com/ericlippert/2009/07/20/iterator-blocks-part-four-why-no-yield-in-catch/
* https://blogs.msdn.microsoft.com/ericlippert/2009/07/23/iterator-blocks-part-five-push-vs-pull/

At the same time it seems necessary to be able to call suspension point in finally blocks within asynchronous coroutines (some close-like operations may be async either).
And moreover async controllers are not supposed to call `executeFinallyBlocks()`, so there is know tricky semantics here.

So my proposal is to allow  suspension points in `finally` blocks by with possibility to prohibit them for specific controller with some annotation/modifier.

**Comment by bsideup** [comment]
Sounds good to me!

**Comment by dzharkov** [comment]
Also there are some potential problems about bytecode correctness, that should be investigated further, like whether jumps into try/catch blocks from outside are allowed by JVM spec

**Comment by abreslav** [comment]
@dzharkov I did some basic tests about that, and it's alright, but we should check the spec nevertheless

**Comment by dzharkov** [comment]
Note that `await` expressions in finally-blocks were supported in C# 6.0, while `yield` is still prohibited for the reasons described above

**Comment by elizarov** [comment]
We don't have any restrictions on suspension points and it covers all the use-cases that we have.
