### ISSUE TITLE
How can I invoke kotlin coroutines from Java code ?

### ISSUE THREAD

**Issue by tinycedar** [Kotlin/kotlin-coroutines#90]
Is it possible to invoke kotlin coroutines from Java code ?

**Comment by elizarov** [comment]
It depends on what you want. You can start by reading this specific question on stackoverflow: http://stackoverflow.com/questions/41559105/can-i-take-advantage-of-kotlins-coroutines-by-using-them-in-java-code 

If that does not answer your question, then you can post your own question there or use the following venues to asking questions:
* Kotlin discussion board https://discuss.kotlinlang.org/ 
* KotlinLang Slack (join coroutines channels): http://slack.kotlinlang.org/
