### ISSUE TITLE
Statistics - Coroutines vs Threads

### ISSUE THREAD

**Issue by vicboma1** [Kotlin/kotlin-coroutines#91]
I'm in an indie development with pure kotlin experimental.
Project : https://github.com/vicboma1/GameBoyEmulatorEnvironment
A week ago I changed threads with Java 8 to coroutines with kotlin and the times are awesome!!! 
Here are the averaging time with 12 executions to load 2546 images in a gridview :
https://github.com/vicboma1/GameBoyEmulatorEnvironment/blob/master/Versioning.md#version-023----wip 

Kotlin coroutines :1st_place_medal:

**Comment by elizarov** [comment]
It would be really great if you share your experience via a blog post or something like this. You are also welcome to join kotlinlang Slack (go to #coroutine channel) to discuss.
